In [40]:
import numpy as np
import pandas as pd
import json


import warnings
warnings.filterwarnings('ignore')

# **EXTRACT DATA**

In [41]:
# Let's Extract Structured Data

prof_loss = pd.read_csv(r'/content/drive/MyDrive/ETL PIPELINE/SRTU_profit_loss.csv')

In [42]:
prof_loss.head()

,S. No.,Name of State Road Transport Undertaking (SRTU),Total Revenue (Rs. Lakh) - 2016-17,Total Revenue (Rs. Lakh) - 2015-16,Total Cost (Rs. Lakh) - 2016-17,Total Cost (Rs. Lakh) - 2015-16,Net Profit/Loss (Rs. Lakh) - 2016-17,Net Profit/Loss (Rs. Lakh) - 2015-16,Profit before Tax (Rs. Lakh) - 2016-17,Profit before Tax (Rs. Lakh) - 2015-16
0,1.0,Andhra Pradesh SRTC,525046.15,505851.96,495154.61,501957.08,29891.54,3894.88,71262.85,27243.76
1,2.0,Assam STC,11950.46,17261.42,18636.11,23791.96,-6685.65,-6530.54,-6590.30,-6438.59
2,3.0,Bangalore Metropolitan TC,210610.41,220748.39,236701.42,219375.73,-26091.01,1372.66,-16212.34,12063.59
3,4.0,Bihar SRTC,6132.28,4868.25,5352.72,11236.86,779.56,-6368.61,884.27,-6282.58
4,5.0,Calcutta STC,35311.19,34884.32,69398.58,48764.56,-34087.39,-13880.24,-34087.39,-13880.24

In [43]:
# Let's read the unstructured data in colab

financial = pd.read_xml(r'/content/drive/MyDrive/ETL PIPELINE/SRTU_financial.xml')
financial.head()

,S._NO.,NAME_OF_STATE_ROAD_TRANSPORT_UNDERTAKING_SRTU,TRAFFIC_REVENUE_LAKH_-_REVENUE_FROM_PASSENGERS_-_2016-17,TRAFFIC_REVENUE_LAKH_-_REVENUE_FROM_PASSENGERS_-_2015-16,TRAFFIC_REVENUE_LAKH_-_OTHERS_-_2016-17,TRAFFIC_REVENUE_LAKH_-_OTHERS_-_2015-16,TRAFFIC_REVENUE_LAKH_-_TOTAL_OF_TRAFFIC_EARNINGS_-_2016-17,TRAFFIC_REVENUE_LAKH_-_TOTAL_OF_TRAFFIC_EARNINGS_-_2015-16,NON-TRAFFIC_REVENUE_LAKH_-_INCOME_FROM_ADVERTISEMENTS_-_2016-17,NON-TRAFFIC_REVENUE_LAKH_-_INCOME_FROM_ADVERTISEMENTS_-_2015-16,...,TAXES_RS._LAKH_-_GST_-_2016-17,TAXES_RS._LAKH_-_GST_-_2015-16,TAXES_RS._LAKH_-_OTHER_TAXES_-_2016-17,TAXES_RS._LAKH_-_OTHER_TAXES_-_2015-16,TAXES_RS._LAKH_-_TOTAL_TAXES_-_2016-17,TAXES_RS._LAKH_-_TOTAL_TAXES_-_2015-16,OTHER_COSTMISCRS._LAKH_-_2016-17,OTHER_COSTMISCRS._LAKH_-_2015-16,TOTAL_COST_IN_LAKH_-_2016-17,TOTAL_COST_IN_LAKH_-_2015-16
0,1.0,Andhra Pradesh SRTC,444775.96,425827.24,0.00,0.00,444775.96,425827.24,1605.18,1217.95,...,0.0,0.0,12045.30,0.00,41371.31,23348.88,0.00,0.00,495154.61,501957.08
1,2.0,Assam STC,6656.19,8849.51,0.00,0.00,6656.19,8849.51,32.63,27.13,...,0.0,0.0,67.35,65.62,95.35,91.95,421.39,409.33,18636.11,23791.96
2,3.0,Bangalore Metropolitan TC,177047.15,191802.62,0.00,0.00,177047.15,191802.62,1399.64,1209.67,...,0.0,0.0,0.00,0.00,9878.67,10690.93,5845.11,5545.29,236701.42,219375.73
3,4.0,Bihar SRTC,3969.68,3969.68,0.00,0.00,3969.68,3969.68,0.00,0.00,...,0.0,0.0,4.30,72.53,104.71,86.03,0.00,407.98,5352.72,11236.86
4,5.0,Calcutta STC,10756.69,9691.31,175.32,80.97,10932.01,9772.28,119.14,207.42,...,0.0,0.0,0.00,0.00,0.00,0.00,32407.54,13462.94,69398.58,48764.56

In [44]:
# read the json file

with open('/content/drive/MyDrive/ETL PIPELINE/SRTU_physical.json', 'r') as file:
  physical = json.load(file)

# **TRANSFORMED THE EXTRACTED DATA**

In [45]:
# Let's Transform Physical Data i

pd.DataFrame(physical['data']).head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,1,Andhra Pradesh SRTC,12072,12012,12031,11931,99.66,99.33,5.46,7.73,...,791406.4,777454.37,538552.05,516978.85,68.05,66.5,24017,22977.48,545.06,522.64
1,2,Assam STC,1067,1090,614,668,57.54,61.28,5.35,4.4,...,8807.21,9943.53,6564.01,7437.69,74.53,74.8,173.94,207.95,44.66,52.13
2,3,Bangalore Metropolitan TC,6270,6439,5579,5856,88.99,90.95,7.64,6.89,...,254004.89,258802.58,174914.33,192031.51,68.86,74.2,17611.25,18570.84,769.57,787.96
3,4,Bihar SRTC,223,223,94,94,42.15,42.15,13.85,12.85,...,3462.24,3570.04,3081.39,3146.03,89,88.12,24.9,26.55,30.59,32.53
4,5,Calcutta STC,773,813,484,454,62.61,55.84,2.96,3.61,...,14125,9576.25,8272,7652.94,58.56,79.92,986,869.3,349.47,292.14

In [46]:
cols = pd.DataFrame(physical['fields'])['label']

In [47]:
phy = pd.DataFrame(physical['data'], columns = cols)

In [48]:
phy.head()

label,S. No.,Name of State Road Transport Undertaking (SRTU),Average Fleet Held (Number) - 2016-17,Average Fleet Held (Number) - 2015-16,Average Fleet Operated (Number) - 2016-17,Average Fleet Operated (Number) - 2015-16,Fleet Utilisation (%) - 2016-17,Fleet Utilisation (%) - 2015-16,Avg Age of Fleet (Years) - 2016-17,Avg Age of Fleet (Years) - 2015-16,...,Passenger Kilometres Offered (Lakh) - 2016-17,Passenger Kilometres Offered (Lakh) - 2015-16,Passenger KMS Performed (Lakh) - 2016-17,Passenger KMS Performed (Lakh) - 2015-16,Occupancy Ratio (%) - 2016-17,Occupancy Ratio (%) - 2015-16,Passengers Carried (Lakh) - 2016-17,Passengers Carried (Lakh) - 2015-16,Passengers carried per Bus/Day (Number) - 2016-17,Passengers carried per Bus/Day (Number) - 2015-16
0,1,Andhra Pradesh SRTC,12072,12012,12031,11931,99.66,99.33,5.46,7.73,...,791406.4,777454.37,538552.05,516978.85,68.05,66.5,24017,22977.48,545.06,522.64
1,2,Assam STC,1067,1090,614,668,57.54,61.28,5.35,4.4,...,8807.21,9943.53,6564.01,7437.69,74.53,74.8,173.94,207.95,44.66,52.13
2,3,Bangalore Metropolitan TC,6270,6439,5579,5856,88.99,90.95,7.64,6.89,...,254004.89,258802.58,174914.33,192031.51,68.86,74.2,17611.25,18570.84,769.57,787.96
3,4,Bihar SRTC,223,223,94,94,42.15,42.15,13.85,12.85,...,3462.24,3570.04,3081.39,3146.03,89,88.12,24.9,26.55,30.59,32.53
4,5,Calcutta STC,773,813,484,454,62.61,55.84,2.96,3.61,...,14125,9576.25,8272,7652.94,58.56,79.92,986,869.3,349.47,292.14

In [49]:
# Lets Merge These 3 Dataframes

# Let's Merge Physical and Financial

phy.shape

(62, 36)

In [50]:
# We have Inconsistency in the data as differ no of rows and columns

In [51]:
a = set(phy['Name of State Road Transport Undertaking (SRTU)'])
b = set(financial['NAME_OF_STATE_ROAD_TRANSPORT_UNDERTAKING_SRTU'])

In [52]:
a.symmetric_difference(b)

{'MEERUT CITY TSL',
 'MEERUT CIY TSL',
 'Total (Reporting SRTUs)',
 'Uttar Pradesh SRTC ',
 'Uttar Pradesh SRTC (P)'}

In [53]:
financial['NAME_OF_STATE_ROAD_TRANSPORT_UNDERTAKING_SRTU'].replace({'MEERUT CIY TSL':'MEERUT CITY TSL',
                                                                    'Uttar Pradesh SRTC (P)' : 'Uttar Pradesh SRTC '}, inplace = True)

In [54]:
a = set(phy['Name of State Road Transport Undertaking (SRTU)'])
b = set(financial['NAME_OF_STATE_ROAD_TRANSPORT_UNDERTAKING_SRTU'])

a.symmetric_difference(b)

{'Total (Reporting SRTUs)'}

In [55]:
df1= phy.merge(financial, left_on='''Name of State Road Transport Undertaking (SRTU)''', right_on= 'NAME_OF_STATE_ROAD_TRANSPORT_UNDERTAKING_SRTU')

In [56]:
df1.head()

,S. No.,Name of State Road Transport Undertaking (SRTU),Average Fleet Held (Number) - 2016-17,Average Fleet Held (Number) - 2015-16,Average Fleet Operated (Number) - 2016-17,Average Fleet Operated (Number) - 2015-16,Fleet Utilisation (%) - 2016-17,Fleet Utilisation (%) - 2015-16,Avg Age of Fleet (Years) - 2016-17,Avg Age of Fleet (Years) - 2015-16,...,TAXES_RS._LAKH_-_GST_-_2016-17,TAXES_RS._LAKH_-_GST_-_2015-16,TAXES_RS._LAKH_-_OTHER_TAXES_-_2016-17,TAXES_RS._LAKH_-_OTHER_TAXES_-_2015-16,TAXES_RS._LAKH_-_TOTAL_TAXES_-_2016-17,TAXES_RS._LAKH_-_TOTAL_TAXES_-_2015-16,OTHER_COSTMISCRS._LAKH_-_2016-17,OTHER_COSTMISCRS._LAKH_-_2015-16,TOTAL_COST_IN_LAKH_-_2016-17,TOTAL_COST_IN_LAKH_-_2015-16
0,1,Andhra Pradesh SRTC,12072,12012,12031,11931,99.66,99.33,5.46,7.73,...,0.0,0.0,12045.30,0.00,41371.31,23348.88,0.00,0.00,495154.61,501957.08
1,2,Assam STC,1067,1090,614,668,57.54,61.28,5.35,4.4,...,0.0,0.0,67.35,65.62,95.35,91.95,421.39,409.33,18636.11,23791.96
2,3,Bangalore Metropolitan TC,6270,6439,5579,5856,88.99,90.95,7.64,6.89,...,0.0,0.0,0.00,0.00,9878.67,10690.93,5845.11,5545.29,236701.42,219375.73
3,4,Bihar SRTC,223,223,94,94,42.15,42.15,13.85,12.85,...,0.0,0.0,4.30,72.53,104.71,86.03,0.00,407.98,5352.72,11236.86
4,5,Calcutta STC,773,813,484,454,62.61,55.84,2.96,3.61,...,0.0,0.0,0.00,0.00,0.00,0.00,32407.54,13462.94,69398.58,48764.56

In [57]:
a = set(df1['Name of State Road Transport Undertaking (SRTU)'])
b = set(prof_loss['Name of State Road Transport Undertaking (SRTU)'])

a.symmetric_difference(b)

{'Kolahpur MTU',
 'Kolhapur MTU',
 'MEERUT CITY TSL',
 'MEERUT CIY TSL',
 'Total (Reporting SRTUs)',
 'Uttar Pradesh SRTC ',
 'Uttar Pradesh SRTC (P)'}

In [58]:
prof_loss['Name of State Road Transport Undertaking (SRTU)'].replace({ 'Uttar Pradesh SRTC (P)' : 'Uttar Pradesh SRTC ',
                                                                        '''MEERUT CIY TSL''' : 'MEERUT CITY TSL',
                                                                         'Kolhapur MTU' : 'Kolahpur MTU'}, inplace = True)

In [59]:
final_data = df1.merge(prof_loss, on = '''Name of State Road Transport Undertaking (SRTU)''')

In [60]:
final_data.drop(columns = ['S. No._x', 'S. No._y'], inplace = True)

In [61]:
final_data.head(2)

,Name of State Road Transport Undertaking (SRTU),Average Fleet Held (Number) - 2016-17,Average Fleet Held (Number) - 2015-16,Average Fleet Operated (Number) - 2016-17,Average Fleet Operated (Number) - 2015-16,Fleet Utilisation (%) - 2016-17,Fleet Utilisation (%) - 2015-16,Avg Age of Fleet (Years) - 2016-17,Avg Age of Fleet (Years) - 2015-16,Over aged vehicles (%) - 2016-17,...,TOTAL_COST_IN_LAKH_-_2016-17,TOTAL_COST_IN_LAKH_-_2015-16,Total Revenue (Rs. Lakh) - 2016-17,Total Revenue (Rs. Lakh) - 2015-16,Total Cost (Rs. Lakh) - 2016-17,Total Cost (Rs. Lakh) - 2015-16,Net Profit/Loss (Rs. Lakh) - 2016-17,Net Profit/Loss (Rs. Lakh) - 2015-16,Profit before Tax (Rs. Lakh) - 2016-17,Profit before Tax (Rs. Lakh) - 2015-16
0,Andhra Pradesh SRTC,12072,12012,12031,11931,99.66,99.33,5.46,7.73,13.29,...,495154.61,501957.08,525046.15,505851.96,495154.61,501957.08,29891.54,3894.88,71262.85,27243.76
1,Assam STC,1067,1090,614,668,57.54,61.28,5.35,4.4,36.4,...,18636.11,23791.96,11950.46,17261.42,18636.11,23791.96,-6685.65,-6530.54,-6590.30,-6438.59

# **LOADING THE FINAL DATA IN DRIVE**

In [62]:
final_data.to_excel(r'/content/drive/MyDrive/ETL PIPELINE/final_data.xlsx')

In [63]:
final_data.shape

(61, 101)